# Generated by Django 5.0.6 on 2024-06-13 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ChatApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="roomm_name",
            new_name="room_name",
        ),
    ]
